#!/usr/bin/env python3
"""THE AGENT AND THE LOOP — train a walking policy with PPO.

Run it:
    python training/train.py --steps 10_000_000 --envs 10

--------------------------------------------------------------------------
THE VOCABULARY, on one screen
--------------------------------------------------------------------------
ENVIRONMENT   the simulated robot and its world.       -> training/env.py
STATE / OBSERVATION
              the 246 numbers the robot can sense.     -> contract.py
ACTION        the 8 numbers the agent outputs.         -> contract.py
REWARD        one number per step saying how good
              that step was.                           -> training/env.py
POLICY        the function ACTION = policy(STATE).
              Here: a neural network, 246 -> 256 -> 256 -> 8.
AGENT         the policy PLUS the machinery that
              improves it. That is PPO. -> this file
LOOP          act, collect, score, update, repeat.     -> this file

--------------------------------------------------------------------------
THE LOOP, in detail
--------------------------------------------------------------------------
Everything below is `model.learn()`. It repeats two phases forever:

  PHASE 1 — COLLECT (no learning happens here)
      Run the current policy in the environment for N steps and write down
      every (state, action, reward) it produced. This is called a ROLLOUT.
      Because nothing is being updated, all the parallel environments can
      run at once; this is why `--envs 10` is roughly 10x faster.

  PHASE 2 — UPDATE (no acting happens here)
      Look at the rollout and ask, for each action taken: did it turn out
      better or worse than expected? Nudge the network to make the
      better-than-expected actions more likely and the others less likely.
      Then throw the rollout away and go back to Phase 1 -- the data was
      generated by the OLD policy and is stale the moment the policy moves.

--------------------------------------------------------------------------
WHAT MAKES IT "PROXIMAL"
--------------------------------------------------------------------------
The obvious version of Phase 2 is unstable. If one lucky rollout suggests a
big change, the network takes it, the policy lurches into a region it has
never explored, collects garbage data, and the run collapses -- with no way
back, because the good policy is already overwritten.

PPO's whole idea is to refuse to move far. It clips each update so the new
policy stays close to the old one, trading a slower climb for not falling off
a cliff. `target_kl` below is a second, harder version of the same guard: if
an update would change the policy's behaviour by more than that, PPO abandons
the rest of the update immediately.

That is the entire trick, and it is why PPO is the default choice for
robotics: it is not the fastest learner, it is the one that does not blow up
overnight while you sleep.

--------------------------------------------------------------------------
TWO NETWORKS, NOT ONE
--------------------------------------------------------------------------
"Better or worse than expected" needs a definition of "expected". So PPO
trains a second network alongside the policy -- the VALUE function, or CRITIC
-- whose only job is to predict the total future reward from a given state.

    ADVANTAGE = (what actually happened) - (what the critic predicted)

Positive advantage means the action beat expectations, so do more of it. The
critic is a measuring stick, discarded at deployment: `robot/run.py` loads
only the policy.

Watch `explained_variance` in the training output. It is how well the critic
predicts reality. Near 0 means the critic is guessing, so the advantages are
noise and the policy is learning nothing useful.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
HERE = Path(__file__).resolve().parent

from env import DEFAULT_URDF, BittleSimEnv  # noqa: E402


def parse_args(argv=None):
    a = argparse.ArgumentParser(description="Train a Bittle walking policy with PPO.")
    a.add_argument("--steps", type=int, default=10_000_000,
                   help="Total environment steps to train for. ~10M gets a gait.")
    a.add_argument("--envs", type=int, default=10,
                   help="Parallel simulators. More = faster, until CPU-bound.")
    a.add_argument("--out", type=Path, default=HERE / "runs" / "walk",
                   help="Where to save models and logs.")
    a.add_argument("--urdf", type=Path, default=DEFAULT_URDF)
    a.add_argument("--seed", type=int, default=42)

    # --- The knobs that matter, and what they trade off -------------------
    a.add_argument("--lr", type=float, default=1e-4,
                   help="Learning rate: how big a step each update takes. "
                        "Too high and the policy thrashes; too low and it "
                        "never gets anywhere.")
    a.add_argument("--target-kl", type=float, default=0.05,
                   help="Hard cap on how much the policy may change per "
                        "update. Set this too tight (0.03 here) and updates "
                        "abort at step 0 -- we once lost 84%% of an entire "
                        "run to that, learning almost nothing.")
    a.add_argument("--ent-coef", type=float, default=0.005,
                   help="Reward for staying random. This is the "
                        "explore-vs-exploit dial: at 0 the policy locks onto "
                        "the first mediocre thing that works and stops "
                        "looking. Early on, exploration is everything.")
    a.add_argument("--check", action="store_true",
                   help="Validate the environment and exit without training.")
    return a.parse_args(argv)


def main(argv=None):
    args = parse_args(argv)

    import warnings

    # SB3 notes that the training envs are parallel while the eval env is a
    # single one. That is deliberate -- see below -- and the warning is noise.
    warnings.filterwarnings("ignore", message="Training and eval env are not of the same type")

    from stable_baselines3 import PPO
    from stable_baselines3.common.callbacks import CallbackList, CheckpointCallback, EvalCallback
    from stable_baselines3.common.env_util import make_vec_env
    from stable_baselines3.common.monitor import Monitor
    from stable_baselines3.common.vec_env import DummyVecEnv, SubprocVecEnv

    if args.check:
        from stable_baselines3.common.env_checker import check_env
        env = BittleSimEnv(args.urdf)
        try:
            check_env(env, warn=True)
            print("environment OK")
        finally:
            env.close()
        return

    args.out.mkdir(parents=True, exist_ok=True)

    # ------------------------------------------------------------------
    # THE ENVIRONMENTS
    # ------------------------------------------------------------------
    # Many independent copies of the robot, each in its own OS process, all
    # stepping at once. They do not interact -- this is purely a way to
    # gather experience faster. Around 10 is the sweet spot on a normal CPU;
    # past that, the cost of shuffling data between processes eats the gain.
    vec_cls = SubprocVecEnv if args.envs > 1 else DummyVecEnv
    envs = make_vec_env(lambda: BittleSimEnv(args.urdf), n_envs=args.envs,
                        vec_env_cls=vec_cls)

    # A separate, single environment used ONLY for scoring. Training rollouts
    # are deliberately random (that is how exploration happens), so their
    # reward is a poor measure of how good the policy actually is. This one
    # runs the policy deterministically -- always its best guess, no dice --
    # and whenever that score improves, `best_model.zip` is overwritten.
    #
    # That file is the safety net. Runs often peak and then degrade; without
    # it you would keep only the final, worse policy.
    eval_env = Monitor(BittleSimEnv(args.urdf))

    # ------------------------------------------------------------------
    # THE AGENT
    # ------------------------------------------------------------------
    model = PPO(
        "MlpPolicy",                            # a plain feed-forward network
        envs,
        seed=args.seed,
        policy_kwargs=dict(net_arch=[256, 256]),  # two hidden layers of 256
        # Steps collected per environment before each update. The product
        # (n_steps x envs) is the total batch -- about 16k steps per update.
        # Bigger batches give less noisy updates but fewer of them.
        # Rounded to a multiple of 64 so it divides evenly into minibatches;
        # otherwise SB3 warns about a ragged last minibatch every run.
        n_steps=max(round(16384 / args.envs / 64) * 64, 64),
        learning_rate=args.lr,
        target_kl=args.target_kl,
        ent_coef=args.ent_coef,
        verbose=1,
        tensorboard_log=str(args.out / "tensorboard"),
    )

    # SB3 counts callback ticks per environment, so divide to get a cadence
    # measured in total environment steps.
    callbacks = CallbackList([
        CheckpointCallback(
            save_freq=max(1_000_000 // args.envs, 1),
            save_path=str(args.out / "checkpoints"), name_prefix="ppo",
        ),
        EvalCallback(
            eval_env, best_model_save_path=str(args.out),
            log_path=str(args.out / "eval"),
            eval_freq=max(100_000 // args.envs, 1),
            n_eval_episodes=3, deterministic=True, verbose=1,
        ),
    ])

    print(f"training {args.steps:,} steps across {args.envs} environments")
    print(f"  best policy will be saved to {args.out / 'best_model.zip'}")
    print(f"  watch it with:  python training/watch.py {args.out / 'best_model.zip'}")

    # ------------------------------------------------------------------
    # THE LOOP — collect, update, repeat, until the step budget runs out.
    # ------------------------------------------------------------------
    try:
        model.learn(total_timesteps=args.steps, callback=callbacks)
        model.save(str(args.out / "final_model"))
        print(f"done. final={args.out / 'final_model.zip'}  "
              f"best={args.out / 'best_model.zip'}")
    finally:
        envs.close()
        eval_env.close()


if __name__ == "__main__":
    main()
